# Generated by Django 5.0.6 on 2026-08-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0002_account_is_cash_account'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_account',
            field=models.ForeignKey(blank=True, help_text='مطلوب فقط إذا كانت الفاتورة تحمل مبلغ خصم', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_discount', to='chart_of_accounts.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_account',
            field=models.ForeignKey(blank=True, help_text='مطلوب فقط إذا كانت الفاتورة تحمل مبلغ ضريبة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_tax', to='chart_of_accounts.account'),
        ),
    ]
