# Generated by Django 5.0.6 on 2026-08-17 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='piece', max_length=20)),
                ('valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('Weighted Average', 'Weighted Average')], default='Weighted Average', max_length=20)),
                ('average_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cogs_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_cogs', to='chart_of_accounts.account')),
                ('inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_inventory', to='chart_of_accounts.account')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Sale', 'Sale'), ('Adjustment', 'Adjustment'), ('Transfer', 'Transfer'), ('Opening', 'Opening')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
