# Generated by Django 5.0.6 on 2026-08-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0002_account_is_cash_account'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='retained_earnings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retained_earnings_years', to='chart_of_accounts.account'),
        ),
    ]
