# Generated by Django 5.0.6 on 2026-08-17 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0001_initial'),
        ('fiscal', '0001_initial'),
        ('journal_entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('useful_life_years', models.PositiveIntegerField()),
                ('depreciation_method', models.CharField(choices=[('Straight-line', 'Straight-line'), ('Declining', 'Declining')], default='Straight-line', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disposed', 'Disposed')], default='Active', max_length=20)),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_asset', to='chart_of_accounts.account')),
                ('depreciation_account', models.ForeignKey(help_text='حساب مجمع الإهلاك (دائن، Contra-Asset)', on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_depreciation', to='chart_of_accounts.account')),
                ('expense_account', models.ForeignKey(help_text='حساب مصروف الإهلاك (مدين)', on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_expense', to='chart_of_accounts.account')),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_posted', models.BooleanField(default=False)),
                ('fiscal_period', models.ForeignKey(blank=True, help_text='يُترك فارغًا عند التوليد المبدئي، ويجب تحديده قبل الترحيل', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_schedules', to='fiscal.fiscalperiod')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_schedules', to='journal_entries.journalentry')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedules', to='fixed_assets.fixedasset')),
            ],
            options={
                'verbose_name': 'Depreciation Schedule',
                'verbose_name_plural': 'Depreciation Schedules',
                'ordering': ['fiscal_period__start_date'],
            },
        ),
    ]
