# Generated by Django 5.0.6 on 2026-08-18 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0002_account_is_cash_account'),
        ('fixed_assets', '0002_alter_fixedasset_expense_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='expense_account',
            field=models.ForeignKey(help_text='حساب مصروف الإهلاك (مدين)', on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_expense', to='chart_of_accounts.account'),
        ),
    ]
