# Generated by Django 5.0.6 on 2026-08-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Invoice', 'Invoice'), ('Payment', 'Payment'), ('Payroll', 'Payroll'), ('Asset', 'Asset'), ('Reversal', 'Reversal'), ('Closing', 'Closing')], default='Manual', max_length=20),
        ),
    ]
