# Generated by Django 5.0.6 on 2026-08-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_cash_account',
            field=models.BooleanField(default=False, help_text='حساب نقدي/بنكي يُستخدم في قائمة التدفقات النقدية'),
        ),
    ]
