# Generated by Django 5.0.6 on 2026-08-19 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptpayment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_payments', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='exchange_rate_used',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=15),
        ),
    ]
