# Generated by Django 5.0.6 on 2026-08-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('JournalEntry', 'Journal Entry'), ('SaleInvoice', 'Sale Invoice'), ('PurchaseInvoice', 'Purchase Invoice'), ('Receipt', 'Receipt'), ('Payment', 'Payment')], max_length=50, unique=True)),
                ('prefix', models.CharField(blank=True, default='', max_length=10)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_sequences', to='fiscal.fiscalyear')),
            ],
            options={
                'verbose_name': 'Document Sequence',
                'verbose_name_plural': 'Document Sequences',
            },
        ),
    ]
