# Generated by Django 5.0.6 on 2026-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('JournalEntry', 'Journal Entry'), ('SaleInvoice', 'Sale Invoice'), ('PurchaseInvoice', 'Purchase Invoice'), ('Receipt', 'Receipt'), ('Payment', 'Payment')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='documentsequence',
            unique_together={('document_type', 'fiscal_year')},
        ),
    ]
